version: '3.4'
services:
  rasa-server:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    volumes:
    - ./actions: /app/actions
    - ./data: /app/data
    - ./models: /app/models
    command: bash -c "rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5006:5005'