version: '3.4'
services:
  rasa:
    image: rasa-server-okteto:latest
    build: "./"
    restart: always
    working_dir: /app
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./actions:/app/actions
    command: bash -c "rasa run --enable-api -p 5006 --cors \"*\""
    ports:
      - '5006:5006'
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"